server:
  port: 8080
  servlet:
    context-path: /diancan
spring:
  datasource:
    url: jdbc:mysql://localhost/diancan?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useOldAliasMetadataBehavior=true&allowPublicKeyRetrieval=true
    username: 'root'
    password: '05040002'
    hikari:
      connection-init-sql: set names utf8mb4
    tomcat:
      init-s-q-l: SET NAMES utf8mb4 #这是最重要的一步
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

